[WIP] Group common logic for browser and node envs
tshemsedinov/wasm-import pull request #19
Opened 2023-08-14 16:33 UTC by rustworthy

- [x] tests and linter show no problems (`npm t`)
- [ ] tests are added/updated for bug fixes and new features
- [x] code is properly formatted (`npm run fmt`)
- [ ] description of changes is added in CHANGELOG.md
- [x] update .d.ts typings

Closes: https://github.com/tshemsedinov/wasm-import/issues/18

2023-08-14 16:36 UTC, rustworthy commented
@tshemsedinov 

Conceptually, what do you make of this approach?
![image](https://github.com/tshemsedinov/wasm-import/assets/117771945/fa55a76e-6f0d-4eed-a254-d2f30c7559c7)

2023-08-19 15:30 UTC, rustworthy commented
I remember you turned down the class-based approach, but I still believe it is worth considering. We could group the common logic in the base class and implement 'compile' method in the sub classes, or use an open constructor. E.g. compile(path) {wa.compile streaming(resp)} for browser, and compile(path) {wa.compile(buffer)} for node

2023-10-29 17:52 UTC, rustworthy commented
Issue with rust binary can be reproduced locally with latest stable rustc. Will figure it out.

![Uploading image.png…]()

2023-11-01 17:05 UTC, rustworthy commented
> Issue with rust binary can be reproduced locally with rustc 1.73. Will figure it out.
> 
> ![image](https://user-images.githubusercontent.com/117771945/278888806-c3ba8ebc-d3e2-4f3b-9083-bc4336333dd5.png)

Fixed with:
https://github.com/tshemsedinov/wasm-import/pull/25

2023-11-02 17:12 UTC, tshemsedinov requested changes
please rename lib/loader to lib/node to see diff

2023-11-04 18:47 UTC, tshemsedinov commented on lib/node.js
> +    : await compileInServerEnv(fileName);
```suggestion
  const compile = opts.browser ? compileInBrowserEnv : compileInServerEnv;
  const compiled = await compile(fileName);
```

2023-11-04 18:49 UTC, tshemsedinov approved these changes

2023-11-04 18:50 UTC, tshemsedinov commented
Need to rebase on master @rustworthy

2023-11-05 17:24 UTC, merged