[WIP]Registery for callbacks
tshemsedinov/wasm-import pull request #20
Opened 2023-08-16 06:59 UTC by rustworthy

- [x] tests and linter show no problems (`npm t`)
- [x] tests are added/updated for bug fixes and new features
- [x] code is properly formatted (`npm run fmt`)
- [x] description of changes is added in CHANGELOG.md
- [ ] update .d.ts typings: not applicable

Changes:
- 'calls' may sound just a little bit confusing, so I suggest renaming this storage to 'callbacksRegistry';
- suggesting here to subclass Registry from Map and add a utility method  `getOrSetDefault`, which makes the code tighter in loader;

2023-08-16 07:25 UTC, tshemsedinov requested changes
Use class syntax please

2023-08-16 07:32 UTC, tshemsedinov commented on lib/node.js
>        if (!callback) return;
We may hide mentioned lines behind `callbacksRegistry.getNext(name);`

2023-08-16 07:34 UTC, tshemsedinov commented on lib/node.js
> +      const callbacks = callbacksRegistry.getOrSetDefault(name, []);
- Do not pass empty array to this method
- Rename `.getOrSetDefault(name)` to `.getCallbacks(name)`

2023-11-05 18:44 UTC, closed without merging

2023-11-05 18:44 UTC, rustworthy commented
Closed in favour of [this one](https://github.com/tshemsedinov/wasm-import/pull/26)